version: "3.9"
services:
  postgres:
    image: postgres
    env_file:
      - database.env
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "Enter_2510" ]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
